### ISSUE TITLE
Identical naming to another R package

### ISSUE THREAD

**Issue by Alik-V** [JohnCoene/typed#1]
Hi John, terrific package, thank you for binding this one for R!
I got a question that is related to the package, but "not really". 
The package is working perfectly when using locally, however when trying to deploy to RStudio Connect, server for some reason is trying to install a package [with a similar name](https://cran.r-project.org/web/packages/typed/index.html) even though `renv.lock` file has a correct specification. 
![image](https://user-images.githubusercontent.com/43731270/141956380-fdb51f57-dcf3-4691-931b-b57da186acf8.png)

I was wondering if you have any suggestions for a course of action in this case. Thanks again

**Comment by JohnCoene** [comment]
Ah yes, since this package Antoine Fabri has created {typed} I see no other way than renaming this package

**Comment by Alik-V** [comment]
Actually, this bug went away by itself just now (which is driving me crazy by itself), but there was another issue with another one of yours that I thought I might mention here (fullPage package).

fullPage is listed as 0.1.1 in docs
![image](https://user-images.githubusercontent.com/43731270/141959869-6282d571-be1c-48a1-a7ef-f366214b2401.png)

however, the only release tag is 0.0.1
![image](https://user-images.githubusercontent.com/43731270/141959940-bed02c2b-5f9f-4fbd-a771-cc3f368d6248.png)

Renv records 0.1.1 in lock file and it trips RStudio Connect since it cannot find that version. Simply changing the value in `renv.lock` solved the issue, but something to be mindful of!

**Comment by JohnCoene** [comment]
Ah... I renamed the package. Maybe best to resintall and snapshot. Sorry.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/typedjs")
```

Function names rename the same

**Comment by Alik-V** [comment]
No problem, sorry for all this trouble.
I was hitting a brick wall last night and decided to seek help this morning before trying to fix it with a fresh mind. Could've saved you some trouble here :)

All your work is appreciated!

**Comment by JohnCoene** [comment]
No, no problem: renaming it should have been done anyways.
